"""init

Revision ID: 71ea3d2a59d8
Revises:
Create Date: 2026-04-11 18:07:40.655654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ea3d2a59d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('slug', sa.String(length=50), nullable=False, comment='URL友好标识'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='分类描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='文章分类表'
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('friend_links',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='链接标题'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='链接地址'),
    sa.Column('logo', sa.String(length=500), nullable=True, comment='链接Logo URL'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='链接描述'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重，值越小越靠前'),
    sa.PrimaryKeyConstraint('id'),
    comment='友情链接表'
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名称'),
    sa.Column('slug', sa.String(length=50), nullable=False, comment='URL友好标识'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='文章标签表'
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱地址'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：user-普通用户，admin-管理员'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文章标题'),
    sa.Column('slug', sa.String(length=200), nullable=False, comment='URL友好标识'),
    sa.Column('content', sa.Text(), nullable=False, comment='Markdown原文内容'),
    sa.Column('content_html', sa.Text(), nullable=True, comment='渲染后的HTML内容'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='文章摘要'),
    sa.Column('cover_image', sa.String(length=500), nullable=True, comment='封面图片URL'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='所属分类ID'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：draft-草稿，published-已发布'),
    sa.Column('is_top', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞数'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章表'
    )
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签ID'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id'),
    comment='文章与标签关联表'
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='所属文章ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='评论者用户ID，用户删除时置空'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='游客评论昵称'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='游客评论邮箱'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父评论ID，支持嵌套回复'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：approved-已审核，pending-待审核，spam-垃圾评论'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章评论表'
    )
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='点赞时间'),
    sa.PrimaryKeyConstraint('user_id', 'article_id'),
    comment='文章点赞记录表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('article_tags')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('friend_links')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
