"""为分类和标签表添加updated_at字段

Revision ID: fe5fda806cfd
Revises: 71ea3d2a59d8
Create Date: 2026-04-17 22:40:21.122078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe5fda806cfd'
down_revision: Union[str, None] = '71ea3d2a59d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'created_by')
    op.drop_column('tags', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='创建人ID'))
    op.add_column('categories', sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='创建人ID'))
    # ### end Alembic commands ###
